application: go-socialcounters
version: 3
runtime: go
api_version: go1

env_variables:
  WHITELIST: ''
  BLACKLIST: ''

handlers:
- url: /.*
  script: _go_app

nobuild_files: (Godeps|services|utils|web|main.go)
