version: '2'

services:
  golang:
    build:
      context: .
      dockerfile: scripts/docker/golang.Dockerfile
    command: ./scripts/docker/cmd.sh
    environment:
      - CLEARDB_DATABASE_URL=mysql://docker:123456@tcp(mysql:3306)/db?parseTime=1
      - FACEBOOK_APP_ID
      - FACEBOOK_APP_SECRET
      - MEMCACHIER_SERVERS=memcached:11211
      - TTL_DEFAULT=10
      - REFRESH_TTL_LEFT_THRESHOLD=5
      - REFRESH_BATCH_SIZE=2
      - VERBOSE=1
    links:
      - memcached
      - mysql
    ports:
      - "8080:8080"
    volumes:
      - ./.data/go/pkg/mod:/go/pkg/mod
      - .:/src
    working_dir: /src

  memcached:
    image: memcached:1.5.16-alpine

  mysql:
    image: mysql:5.7.23
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_PASSWORD=123456
      - MYSQL_RANDOM_ROOT_PASSWORD=1
      - MYSQL_USER=docker
    ports:
      - "3306:3306"
    volumes:
      - ./.data/mysql:/var/lib/mysql:rw
