runtime: go
api_version: go1.9

env_variables:
  CONFIG_SECRET: gahtUM4YUXSRKuumcucV7dz8jUm4PCd5

handlers:
- url: /.*
  script: _go_app

liveness_check:
  path: "/"

readiness_check:
  path: "/v2/js/data.json?url=https://facebook.com"
  timeout_sec: 10
